group: apps
version: v1
resource: deployments
object:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: test-oka
    template:
      metadata:
        labels:
          app: test-oka
      spec:
        containers:
          - name: web-oka
            image: nginx:1.12
            ports:
              - name: oka
                protocol: TCP
                containerPort: 80
